smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256
quarkus.native.resources.includes=publicKey.pem,privateKey.pem

mp.jwt.verify.issuer=tu-varna
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=JwtToken

quarkus.log.level=DEBUG

quarkus.http.port=8090