smallrye.jwt.sign.key.location=classpath:privateKey.pem
smallrye.jwt.encrypt.key.location=classpath:publicKey.pem

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256
mp.jwt.verify.issuer=tu-varna
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=JwtToken

quarkus.native.resources.includes=publicKey.pem,privateKey.pem


quarkus.log.level=DEBUG

quarkus.http.port=8090